### ISSUE TITLE
where is docker-zookeeper?

### ISSUE THREAD

**Issue by cloudmode** [appcelerator/amp-docker-kafka#1]
I found the docker image on docker hub, and it appears to be using the joyent containerPilot. I'd like to take a look at it, but the appcelerator/docker-zookeeper link returns a 404.

Thanks in advance.

**Comment by konobi** [comment]
I'd also like to have a look at the docker-zookeeper repo.

**Comment by cloudmode** [comment]
I've put put up a full zookeeper/kafka docker implementation. its at github.com/vescel

**Comment by bertrand-quenin** [comment]
Hi, our zookeeper dokcer image is available here: https://github.com/appcelerator/amp-docker-zookeeper
